language:
  ruby

rvm:
    - 2.7

services:
     - postgresql

before_script:
  - psql -c 'CREATE DATABASE makersbnb_test;' -U postgres
  - psql  -U postgres makersbnb_test < db/migrations/01_create_users_table.sql
  - psql  -U postgres makersbnb_test < db/migrations/02_create_spaces_table.sql

script:
  - bundle exec rspec
